import  ButtonAppBar from "../app/components/NavBar/iu/NavBar.ui"
export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}
import { Routes } from "./models";


export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
      {children}</body>
    </html>
  )
}
